# Generated by Django 5.0 on 2025-04-25 21:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_type', models.CharField(choices=[('births', 'Births'), ('marriages', 'Marriages'), ('deaths', 'Deaths'), ('other', 'Other')], max_length=20)),
                ('file_path', models.CharField(max_length=255)),
                ('date_column', models.CharField(max_length=100)),
                ('surname_column', models.CharField(max_length=100)),
                ('fs_column', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Data Source',
                'verbose_name_plural': 'Data Sources',
            },
        ),
        migrations.CreateModel(
            name='SummaryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('total_records', models.IntegerField()),
                ('missing_values', models.IntegerField()),
                ('unique_years', models.IntegerField()),
                ('records_in_fs', models.IntegerField()),
                ('unique_surnames', models.IntegerField()),
                ('additional_data', models.TextField(blank=True, null=True)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_statistics', to='dashboard.datasource')),
            ],
            options={
                'verbose_name': 'Summary Statistics',
                'verbose_name_plural': 'Summary Statistics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Visualization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('visualization_type', models.CharField(choices=[('bar', 'Bar Chart'), ('line', 'Line Chart'), ('pie', 'Pie Chart'), ('scatter', 'Scatter Plot'), ('histogram', 'Histogram'), ('heatmap', 'Heatmap'), ('other', 'Other')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.TextField(blank=True, null=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizations', to='dashboard.datasource')),
            ],
            options={
                'verbose_name': 'Visualization',
                'verbose_name_plural': 'Visualizations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValueCounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('column_name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='value_counts', to='dashboard.datasource')),
            ],
            options={
                'verbose_name': 'Value Counts',
                'verbose_name_plural': 'Value Counts',
                'ordering': ['-timestamp', '-count'],
                'unique_together': {('data_source', 'column_name', 'value', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='YearlyComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('year', models.IntegerField()),
                ('total_records', models.IntegerField()),
                ('records_with_condition', models.IntegerField()),
                ('condition_name', models.CharField(default='in_fs', max_length=50)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_comparisons', to='dashboard.datasource')),
            ],
            options={
                'verbose_name': 'Yearly Comparison',
                'verbose_name_plural': 'Yearly Comparisons',
                'ordering': ['-timestamp', 'year'],
                'unique_together': {('data_source', 'year', 'timestamp', 'condition_name')},
            },
        ),
    ]
